name: goApiTemplate

services:
  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - "${VALKEY_PORT}:6379"
    environment:
      VALKEY_PASSWORD: ${VALKEY_PASSWORD}
      VALKEY_DATABASES: ${VALKEY_DATABASES}
    command: ["valkey-server", "--requirepass", "${VALKEY_PASSWORD}"]
    volumes:
      - goApiTemplate_valkey_data:/data
    networks:
      - backend

  postgres:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - goApiTemplate_postgres_data:/var/lib/postgresql/18/main
    networks:
      - backend


volumes:
  goApiTemplate_valkey_data:
  goApiTemplate_postgres_data:

networks:
  backend:
    driver: bridge
